/**
 * Sprint 1 — Cross-Tenant Access Integration Tests
 *
 * Tests the full HTTP API surface for tenant isolation.
 * These are BLOCKING in CI/CD — any CRITICAL failure halts deployment.
 *
 * Run: npx vitest run tests/sprint1/test_cross_tenant_access.ts
 * Requires: AUTH_SERVICE_URL, PAM_SERVICE_URL, TENANT_REGISTRY_URL env vars
 *           pointing at a running test environment with seeded data.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';

// ---------------------------------------------------------------------------
// Test environment configuration
// ---------------------------------------------------------------------------
const AUTH_URL = process.env['AUTH_SERVICE_URL'] ?? 'http://localhost:3001';
const PAM_URL = process.env['PAM_SERVICE_URL'] ?? 'http://localhost:3002';
const REGISTRY_URL = process.env['TENANT_REGISTRY_URL'] ?? 'http://localhost:3003';

// Fixture tenant IDs seeded in the test database
const TENANT_A_ID = 'aaaaaaaa-0000-0000-0000-000000000001';
const TENANT_B_ID = 'bbbbbbbb-0000-0000-0000-000000000002';

// These tokens are issued by the test auth-service for the seeded users
// In CI, they are generated by a setup script before the test run.
let tokenTenantA: string;
let tokenTenantB: string;
let adminTokenTenantA: string;
let expiredToken: string;
let tamperedToken: string;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
async function post(url: string, body: unknown, token?: string): Promise<Response> {
  return fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    body: JSON.stringify(body),
  });
}

async function get(url: string, token?: string): Promise<Response> {
  return fetch(url, {
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
}

// ---------------------------------------------------------------------------
// Setup: obtain test tokens from the auth service
// ---------------------------------------------------------------------------
beforeAll(async () => {
  // In a real CI environment these would be pre-seeded WebAuthn credentials
  // replaced with a test-only password flow. For integration testing we use
  // a dedicated test token endpoint enabled only in NODE_ENV=test.
  const issueTestToken = async (tenantId: string, role: string, clientAccess?: string[]) => {
    const res = await post(`${AUTH_URL}/test/issue-token`, {
      tenantId,
      role,
      clientAccess,
    });
    if (!res.ok) {
      throw new Error(`Failed to issue test token for tenant ${tenantId}: ${await res.text()}`);
    }
    const body = await res.json() as { accessToken: string };
    return body.accessToken;
  };

  tokenTenantA = await issueTestToken(TENANT_A_ID, 'auditor');
  tokenTenantB = await issueTestToken(TENANT_B_ID, 'auditor');
  adminTokenTenantA = await issueTestToken(TENANT_A_ID, 'admin');

  // Craft tokens for negative tests
  expiredToken = 'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwidGVuYW50X2lkIjoiYWFhYWFhYWEtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwicm9sZSI6ImF1ZGl0b3IiLCJpYXQiOjE2MDAwMDAwMDAsImV4cCI6MTYwMDAwMDAwMSwianRpIjoiZXhwaXJlZC10ZXN0LXRva2VuIn0.invalid_signature';
  tamperedToken = tokenTenantA.slice(0, -10) + 'tampered12';
});

// ---------------------------------------------------------------------------
// CRITICAL: JWT validation tests
// ---------------------------------------------------------------------------
describe('[CRITICAL] JWT Validation', () => {
  it('401 when no Authorization header is provided', async () => {
    const res = await get(`${AUTH_URL}/auth/me`);
    expect(res.status).toBe(401);
  });

  it('401 (not 403 or 200) when JWT is expired', async () => {
    const res = await get(`${AUTH_URL}/auth/me`, expiredToken);
    expect(res.status).toBe(401);
    const body = await res.json() as { error: string };
    expect(body.error).toBe('invalid_token');
  });

  it('401 when JWT signature is tampered', async () => {
    const res = await get(`${AUTH_URL}/auth/me`, tamperedToken);
    expect(res.status).toBe(401);
  });

  it('401 when JWT has tenant_id removed from payload', async () => {
    // Craft a JWT without tenant_id (base64url decode header+payload, remove claim, re-encode)
    const parts = tokenTenantA.split('.');
    if (parts.length !== 3) throw new Error('Invalid token format');
    const payload = JSON.parse(Buffer.from(parts[1]!, 'base64url').toString()) as Record<string, unknown>;
    delete payload['tenant_id'];
    const tamperedPayload = Buffer.from(JSON.stringify(payload)).toString('base64url');
    const noTenantToken = `${parts[0]}.${tamperedPayload}.${parts[2]}`;
    const res = await get(`${AUTH_URL}/auth/me`, noTenantToken);
    expect(res.status).toBe(401);
  });

  it('Valid token returns 200 with correct tenant context', async () => {
    const res = await get(`${AUTH_URL}/auth/me`, tokenTenantA);
    expect(res.status).toBe(200);
    const body = await res.json() as { tenantId: string };
    expect(body.tenantId).toBe(TENANT_A_ID);
  });
});

// ---------------------------------------------------------------------------
// CRITICAL: Cross-tenant evidence isolation via API
// ---------------------------------------------------------------------------
describe('[CRITICAL] Cross-Tenant Evidence Isolation', () => {
  it('Tenant A token cannot retrieve Tenant B evidence records', async () => {
    // This endpoint returns evidence for the authenticated tenant
    const res = await get(`${AUTH_URL}/evidence?tenantId=${TENANT_B_ID}`, tokenTenantA);
    // Either 403 (rejected before query) or 200 with empty data (RLS filtering)
    if (res.status === 200) {
      const body = await res.json() as { records: unknown[] };
      expect(body.records).toHaveLength(0);
    } else {
      expect(res.status).toBeOneOf([403, 404]);
    }
  });

  it('Tenant B token cannot retrieve Tenant A evidence records', async () => {
    const res = await get(`${AUTH_URL}/evidence?tenantId=${TENANT_A_ID}`, tokenTenantB);
    if (res.status === 200) {
      const body = await res.json() as { records: unknown[] };
      expect(body.records).toHaveLength(0);
    } else {
      expect(res.status).toBeOneOf([403, 404]);
    }
  });

  it('Tenant A token cannot list Tenant B users', async () => {
    const res = await get(`${REGISTRY_URL}/tenants/${TENANT_B_ID}`, tokenTenantA);
    expect([403, 404]).toContain(res.status);
  });
});

// ---------------------------------------------------------------------------
// CRITICAL: PAM Broker access enforcement
// ---------------------------------------------------------------------------
describe('[CRITICAL] PAM Broker Isolation', () => {
  it('readonly role cannot request database_infra access', async () => {
    // Issue a readonly token for tenant A
    const readonlyToken = await (async () => {
      const res = await post(`${AUTH_URL}/test/issue-token`, {
        tenantId: TENANT_A_ID,
        role: 'readonly',
      });
      const body = await res.json() as { accessToken: string };
      return body.accessToken;
    })();

    const res = await post(`${PAM_URL}/access/request`, {
      resource_type: 'database_infra',
      justification: 'Attempting infra access as readonly role',
      requested_duration_seconds: 300,
    }, readonlyToken);

    expect(res.status).toBe(403);
  });

  it('auditor role can request database_readonly access', async () => {
    const res = await post(`${PAM_URL}/access/request`, {
      resource_type: 'database_readonly',
      justification: 'Reviewing Q3 evidence for SOC 2 audit engagement',
      itsm_ticket_id: 'AUDIT-1234',
      requested_duration_seconds: 14400,
    }, tokenTenantA);

    // 200 = approved with credential, 201 = created/pending
    expect([200, 201]).toContain(res.status);
    const body = await res.json() as { status: string; approved_duration_seconds: number };
    expect(body.status).toBe('approved');
    // TTL must be capped at max (28800s = 8h) and default is 4h
    expect(body.approved_duration_seconds).toBeLessThanOrEqual(28800);
    expect(body.approved_duration_seconds).toBeGreaterThan(0);
  });

  it('TTL is capped at maximum for auditor role', async () => {
    const res = await post(`${PAM_URL}/access/request`, {
      resource_type: 'database_readonly',
      justification: 'Testing TTL cap enforcement for compliance validation purposes',
      requested_duration_seconds: 999999, // Request ridiculously long TTL
    }, tokenTenantA);

    const body = await res.json() as { approved_duration_seconds: number };
    // Must be capped at 28800 (8 hours max)
    expect(body.approved_duration_seconds).toBeLessThanOrEqual(28800);
  });

  it('infra access TTL is capped at 15 minutes', async () => {
    const res = await post(`${PAM_URL}/access/request`, {
      resource_type: 'database_infra',
      justification: 'Emergency infra access for incident response on prod incident INC-9999',
      requested_duration_seconds: 3600, // Request 1 hour
    }, adminTokenTenantA);

    if (res.status === 200 || res.status === 201) {
      const body = await res.json() as { approved_duration_seconds: number };
      // Must be capped at 900 (15 minutes max)
      expect(body.approved_duration_seconds).toBeLessThanOrEqual(900);
    }
    // 403 is also acceptable if the test environment's Vault isn't configured for infra
  });

  it('Break-glass access requires dual approval and returns pending status', async () => {
    const res = await post(`${PAM_URL}/access/request`, {
      resource_type: 'break_glass',
      justification: 'Critical production incident — all normal access channels unavailable',
      requested_duration_seconds: 900,
    }, adminTokenTenantA);

    expect([200, 201]).toContain(res.status);
    const body = await res.json() as { status: string };
    // Must be pending until second admin approves
    expect(body.status).toBe('pending');
  });

  it('PAM audit log returns 403 to non-admin roles', async () => {
    const res = await get(`${PAM_URL}/access/audit-log`, tokenTenantA); // auditor role
    expect(res.status).toBe(403);
  });
});

// ---------------------------------------------------------------------------
// HIGH: Tenant Registry isolation
// ---------------------------------------------------------------------------
describe('[HIGH] Tenant Registry Isolation', () => {
  it('Non-admin role cannot create a new tenant', async () => {
    const res = await post(`${REGISTRY_URL}/tenants`, {
      display_name: 'Attacker Tenant',
      tier: 'smb_pool',
      region: 'us-east-1',
    }, tokenTenantA); // auditor token, not admin

    expect(res.status).toBe(403);
  });

  it('firm_partner with no client_access cannot view arbitrary tenant', async () => {
    const firmToken = await (async () => {
      const res = await post(`${AUTH_URL}/test/issue-token`, {
        tenantId: TENANT_A_ID,
        role: 'firm_partner',
        clientAccess: [], // Empty — no clients linked
      });
      const body = await res.json() as { accessToken: string };
      return body.accessToken;
    })();

    const res = await get(`${REGISTRY_URL}/tenants/${TENANT_B_ID}`, firmToken);
    expect([403, 404]).toContain(res.status);
  });

  it('GET /tenants/{id} returns own tenant for auditor role', async () => {
    const res = await get(`${REGISTRY_URL}/tenants/${TENANT_A_ID}`, tokenTenantA);
    expect(res.status).toBe(200);
    const body = await res.json() as { tenant_id: string };
    expect(body.tenant_id).toBe(TENANT_A_ID);
  });
});

// ---------------------------------------------------------------------------
// HIGH: JWKS and token signing
// ---------------------------------------------------------------------------
describe('[HIGH] JWKS Endpoint', () => {
  it('JWKS endpoint returns valid JWK set without authentication', async () => {
    const res = await get(`${AUTH_URL}/.well-known/jwks.json`);
    expect(res.status).toBe(200);
    const body = await res.json() as { keys: Array<{ kty: string; alg: string; use: string }> };
    expect(body.keys).toBeDefined();
    expect(body.keys.length).toBeGreaterThan(0);
    const key = body.keys[0]!;
    expect(key.kty).toBe('RSA');
    expect(key.alg).toBe('RS256');
    expect(key.use).toBe('sig');
  });

  it('JWKS response includes appropriate cache headers', async () => {
    const res = await get(`${AUTH_URL}/.well-known/jwks.json`);
    const cacheControl = res.headers.get('cache-control');
    expect(cacheControl).toContain('max-age');
  });

  it('Private key material is NOT exposed in JWKS', async () => {
    const res = await get(`${AUTH_URL}/.well-known/jwks.json`);
    const body = await res.json() as { keys: Array<Record<string, unknown>> };
    for (const key of body.keys) {
      // RSA private key components must never appear
      expect(key['d']).toBeUndefined();
      expect(key['p']).toBeUndefined();
      expect(key['q']).toBeUndefined();
      expect(key['dp']).toBeUndefined();
      expect(key['dq']).toBeUndefined();
    }
  });
});

// ---------------------------------------------------------------------------
// HIGH: Token revocation
// ---------------------------------------------------------------------------
describe('[HIGH] Token Revocation', () => {
  it('Revoked access token is rejected on subsequent requests', async () => {
    // Issue a short-lived token for this test
    const shortLivedToken = await (async () => {
      const res = await post(`${AUTH_URL}/test/issue-token`, {
        tenantId: TENANT_A_ID,
        role: 'readonly',
      });
      const body = await res.json() as { accessToken: string };
      return body.accessToken;
    })();

    // Verify it works first
    const beforeRevoke = await get(`${AUTH_URL}/auth/me`, shortLivedToken);
    expect(beforeRevoke.status).toBe(200);

    // Revoke it
    const revokeRes = await post(`${AUTH_URL}/auth/token/revoke`, {}, shortLivedToken);
    expect(revokeRes.status).toBe(200);

    // Now it must be rejected
    const afterRevoke = await get(`${AUTH_URL}/auth/me`, shortLivedToken);
    expect(afterRevoke.status).toBe(401);
  });
});

// ---------------------------------------------------------------------------
// MEDIUM: ZK proof cross-tenant submission check (API layer)
// ---------------------------------------------------------------------------
describe('[MEDIUM] ZK Proof Isolation', () => {
  it('Tenant B cannot submit a ZK proof for Tenant A evidence', async () => {
    // Attempt to associate a proof with a Tenant A evidence record using Tenant B token
    const res = await post(`${AUTH_URL}/evidence/proof`, {
      evidence_id: '00000000-0000-0000-0000-000000000001', // Fake Tenant A evidence ID
      circuit_type: 'sum_threshold',
      proof_blob: 'aGVsbG8=', // base64 placeholder
      public_inputs: { sum: 1000, threshold: 50000 },
    }, tokenTenantB);

    // Should be 403 or 404 — never 200
    expect([403, 404]).toContain(res.status);
  });
});

// ---------------------------------------------------------------------------
// Service health checks (block CI if services are down)
// ---------------------------------------------------------------------------
describe('Service Health', () => {
  it('auth-service is healthy', async () => {
    const res = await get(`${AUTH_URL}/health`);
    expect(res.status).toBe(200);
    const body = await res.json() as { status: string };
    expect(body.status).toBe('ok');
  });

  it('pam-broker is healthy', async () => {
    const res = await get(`${PAM_URL}/health`);
    expect(res.status).toBe(200);
  });

  it('tenant-registry is healthy', async () => {
    const res = await get(`${REGISTRY_URL}/health`);
    expect(res.status).toBe(200);
  });
});
